---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: chomkeos
description: Custom personal Fedora Atomic image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  - type: files
    files:
      - source: release
        destination: /

  - type: default-flatpaks
    notify: true
    system: {}
    user: {}

  - from-file: gaming/steam.yml
  - from-file: gaming/heroic.yml

  # Setting up proper signing of images
  - type: signing # this sets up the proper policy & signing files for signed images to work fully